services:
  postgres:
    image: postgres:alpine
    container_name: postgres-alpine
    environment:
      POSTGRES_DB: bitebyte
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bitepassword
    ports:
      - "5432:5432"
    volumes:
      - ./sql-scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
